name = "MyCustomSkillsPack"
author = "Developer"
version = "1.0.0"
pack-format = "packwiz:v1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f0feb0d6706da18afff2f45c2591c5ca4514484f3a8a1bd39c8989ea1e3fdd2"

[versions]
minecraft = "1.20.1"
