name = "MyCustomSkillsPack"
author = "Developer"
version = "1.0.0"
pack-format = "packwiz:v1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c3aa3eb31272e9cd84e5d6008449b71ee84ef7873a6a81ebe09e4507c1c171"

[versions]
minecraft = "1.20.1"
