name = "L'Ender's Cataclysm"
filename = "L_Enders_Cataclysm-3.16.jar"
side = "both"

[download]
url = "https://github.com/maximyka/RPGmodpackMinecraft/releases/download/untagged-6ec22ff1c85beecd98e2/L_Enders_Cataclysm-3.16.jar"